# powerlevel10k config
function sp {
    git branch > /dev/null 2>&1 || return 1
    git config user.initials
}

POWERLEVEL9K_MODE='nerdfont-complete'
# POWERLEVEL9K_MODE='nerdfont-fontconfig'
POWERLEVEL9K_DIR_BACKGROUND="clear"
# POWERLEVEL9K_CUSTOM_GIT_PAIR="echo \$(sp)"
# POWERLEVEL9K_CUSTOM_GIT_PAIR_BACKGROUND="clear"
# POWERLEVEL9K_CUSTOM_GIT_PAIR_FOREGROUND="001"
# POWERLEVEL9K_CUSTOM_GIT_PAIR_ICON="\uf7af"

POWERLEVEL9K_HOME_ICON="%F{081}\uf015 "
POWERLEVEL9K_HOME_SUB_ICON="%F{081}\uf07c "
POWERLEVEL9K_FOLDER_ICON="%F{081}\uf015 "
POWERLEVEL9K_ETC_ICON=''
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="clear"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="219"
POWERLEVEL9K_DIR_FOREGROUND='219'
POWERLEVEL9K_DIR_HOME_BACKGROUND="clear"
POWERLEVEL9K_DIR_HOME_FOREGROUND="219"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="clear"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="219"
POWERLEVEL9K_DIR_PATH_SEPARATOR="%F{219}/%F{cyan}"
# POWERLEVEL9K_ETC_ICON="$(print_icon 'LEFT_SUBSEGMENT_SEPARATOR')"

POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="red1"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND="clear"

# POWERLEVEL9K_INSTALLATION_PATH=$ANTIGEN_BUNDLES/bhilburn/powerlevel9k

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon root_indicator dir dir_writable_joined custom_git_pair vcs_joined)
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='%F{248}\uf460%F{248}'

POWERLEVEL9K_LINUX_UBUNTU_ICON="\uf31b"
POWERLEVEL9K_OS_ICON_BACKGROUND='clear'
POWERLEVEL9K_OS_ICON_FOREGROUND='mediumspringgreen'

POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{248} \uf101 "

POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status time user)
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''
POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='%F{248}\uf47d%F{248}'

POWERLEVEL9K_SHORTEN_DELIMITER='%F{219}…%F{219}'
POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
POWERLEVEL9K_SHORTEN_STRATEGY="none"

POWERLEVEL9K_STATUS_ERROR_BACKGROUND="clear"
POWERLEVEL9K_STATUS_ERROR_FOREGROUND="red1"
POWERLEVEL9K_STATUS_OK_FOREGROUND="mediumspringgreen"
POWERLEVEL9K_STATUS_OK_BACKGROUND="clear"
POWERLEVEL9K_STATUS_BACKGROUND="clear"
POWERLEVEL9K_CARRIAGE_RETURN_ICON="\uf071"

POWERLEVEL9K_TIME_BACKGROUND=clear
POWERLEVEL9K_TIME_FOREGROUND=226

POWERLEVEL9K_USER_ICON="\uf31c"
POWERLEVEL9K_USER_DEFAULT_BACKGROUND='clear'
POWERLEVEL9K_USER_DEFAULT_FOREGROUND='214'

POWERLEVEL9K_VCS_BACKGROUND='clear'
POWERLEVEL9K_VCS_FOREGROUND='green'
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='clear'
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='green'
# POWERLEVEL9K_VCS_CLEAN_ICON='green'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='clear'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='orange3'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='clear'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='yellow'
POWERLEVEL9K_VCS_GIT_ICON='\uf408 '
